version: "3.4"
services:
  api-gateway:
    container_name: api-gateway
    build:
      context: "./api-gateway"
      dockerfile: "Dockerfile"
    depends_on:
      - chat-service
      - users-service
    ports:
      - "7000:7000"
    volumes:
      - ./api-gateway:/opt/app
      - /opt/app/node_modules
    command: npx ts-node-dev --respawn --poll --files index.dev.ts

  chat-service:
    container_name: chat-service
    build:
      context: "./chat-service"
      dockerfile: "Dockerfile"
    depends_on:
      - chat-service-db
      - rabbitmq
    ports:
      - "7100:7100"
    volumes:
      - ./chat-service:/opt/app
      - /opt/app/node_modules
    command: sh -c "npm run swagger-autogen && npx ts-node-dev --respawn --poll --files index.dev.ts"

  chat-service-db:
    container_name: chat-service-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - "7200:3306"

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "15672:15672"  # Management interface
      - "5672:5672"    # RabbitMQ server
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - "./rabbitmq/data:/var/lib/rabbitmq"
      - "./rabbitmq/log:/var/log/rabbitmq"

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - "7300:80"
  #   volumes:
  #     - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

  users-service:
    container_name: users-service
    build:
      context: "./users-service"
      dockerfile: "Dockerfile"
    depends_on:
      - users-service-db
    ports:
      - "7101:7101"
    volumes:
      - ./users-service:/opt/app
      - /opt/app/node_modules
    command: npx ts-node-dev --respawn --poll --files index.dev.ts

  users-service-db:
    container_name: users-service-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - "7201:3306"

  notification-service:
    container_name: notification-service
    build:
      context: "./notification-service"
      dockerfile: "Dockerfile"
    depends_on:
      - notification-service-db
    ports:
      - "7102:7102"
    volumes:
      - ./notification-service:/opt/app
      - /opt/app/node_modules
    command: npx ts-node-dev --respawn --poll --files index.dev.ts

  notification-service-db:
    container_name: notification-service-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - "7202:3306"

